/**
 * IMAGE BLUR PLACEHOLDERS FOR NEXT/IMAGE
 * Automatically generated by scripts/optimize-images.mjs
 */

export const IMAGE_BLURS: Record<string, string> = {
  "arac-filosu": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARJV8OGSjZCWAAP7IShX7cxUTydxpDkkFcgD9Rmd1jHtHGKdZIezmToTVgt4oFclHV5qE5y6OAAA=",
  "asansor-kurulum": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZwAARcViLIvKfXatgAAA/taujXs3M22+w9bfvyVnVBsyh5qC2mW6IaPZBbYR/yVExW4SSopbVArf/YDShAAA",
  "ekip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoUAA8APzmEuVOvKKWisAgB4CcJZQAIEAPUcm7nNejqP8xdIAD8qvtZiVhvBZ4iqQiyBn0Xcmybzruerdq1Zz/1949cTzvgyFk23kKCeTZ4oj7rmHIwkBvfAuL0sYlZ6NJrYyCVgneWjUV/MoFMepMDAAA=",
  "marangozluk": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJYgCw7CLbaiQYQWAAzgYAfIhF+h+lrqowLY+BMYW2osulu4f6BQmdayIazgQ5OwL8MXi1YR7XXM2fjS33cTP6E5IFnYAA",
  "paketleme-detay": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAA8APzmEuVOvKKWisAgB4CcJQBOmUABr6mZdD4lfe3/K1DwAziTdjMItQbcn5Zh7Qur/asvaUtCVOIjyscMflhVp+BFGw9JZwdEm34l+w0dGHz6WAC8O0wYjFVO5wpKjfGCIv/LorQAA",
  "slayt-1": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJYwCo9BnaR4rWbRYAAP5laXDBlA0OvnZSboZOwe//rpGNQ0oz0gyue/LEnz3OCnlNZR9v8CcDcHnnw6+IIBC3suMlLhq8PhEn5GcEAAA=",
  "slayt-2": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAAsAPzmGulQvKSWjMAgB4CcJQBUeg0fhf6RjvKXcMAD+Uor9MP5inADYyb0AopTBqUlfbiZDt4JxDDBHsT/m14wLzVf1sgVuvE1LRjQudKxAFJ9cAmIAAAA=",
  "slayt-3": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJYgC06BXbvgKoO5NVXgAA/c9giW5YY8W8bXrtq6Pdgxh4CcLsWYh4A8TMxs6tuT6k9aSqiulUQw0W1ISk5iaxYT/NSIdAjh41wNoAAAA="
};
