/**
 * IMAGE BLUR PLACEHOLDERS FOR NEXT/IMAGE
 * Automatically generated by scripts/optimize-images.mjs
 */

export const IMAGE_BLURS: Record<string, string> = {
  "arac-filosu": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARJV8OGSjQYAA/shKFftzFRPJ3GkOSQVyAP1GZ3WMe1n3d6J9qPxvQyloCR6uYiAZYXyUybxQAAA=",
  "asansor-kurulum": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARcViLIvKfXatgAAA/taujXs3M22+w9bfvyVnVBmM1BbTLdENHsgtsI/5KiYrcJJUUtp11ooAaUIAAA==",
  "ekip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQAwCdASoUAA8APzmEuVOvKKWisAgB4CcJZQAAWju3X5SXAOvQG8AA/KvqCeKLzI49M8TBd7jB9HtehyqMzXKZGekdTmukJSM5C9BKljprrE7v+kn7rmHIwkBtYWSpTk3jCDLJKQKHfMbB+s+BzqJUiAA=",
  "marangozluk": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJYgCw7CLc5F8jHIhAAM4GAHyIMIOEdfWVhXSc/t2yIlHtqVYcEKNYKiQQ2nlzYUv8HZ+oo8+ngWhz2OnoaIOLRWeoyYgA",
  "paketleme-detay": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAA8APzmEuVOvKKWisAgB4CcJQBOmUABr6mZdD4lfe3/K1DwAziTdjMItQbcn5Zh7Qur/asvaUtCVOIjyscMflhVp+BFGw9JZwdEm34l+w0dGHz6WAC8O0wYjFVO5wpKjfGCIv/LorQAA",
  "slayt-1": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARJV8OGSjQYAA/shKFftzFRPJ3GkOSQVyAP1GZ3WMe1n3d6J9qPxvQyloCR6uYiAZYXyUybxQAAA=",
  "slayt-2": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZwAARcViLIvKfXatgAAA/taujXs3M22+w9bfvyVnVBmM1BbTLdENHsgtsI/5KiYrcJJUUtp11ooAaUIAAA==",
  "slayt-3": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJYgCw7CLc5F8jHIhAAM4GAHyIMIOEdfWVhXSc/t2yIlHtqVYcEKNYKiQQ2nlzYUv8HZ+oo8+ngWhz2OnoaIOLRWeoyYgA"
};
