export const introText = "Mersin Uzman Eller Nakliyat, Mersin'den İç Anadolu bölgesinin giriş kapısı olan Niğde'ye (Bor dahil) yasal K3 yetki belgeli nakliye araçları, dış cephe asansör sistemleri ve eğitimli ekipleriyle profesyonel evden eve taşıma çözümleri sunmaktadır. Toros dağ geçişlerinde tecrübeli şoförlerimiz eşyalarınızı sarsıntısız ve güvenle taşır. Uzman Eller Nakliyat güvencesiyle Niğde taşımalarınızda sabit fiyat ve marangoz montaj garantisi sunulur.";
export const distanceText = "Mersin ile Niğde arası karayolu mesafesi O-21 otoyolu üzerinden yaklaşık 200 kilometredir. Ev eşyası taşıyan araçlarımızın sürüş süresi ortalama 2.5 saattir. Sabah saat 08:00'de başlayan ambalajlama ve yükleme adımlarının ardından öğle saatlerinde yola çıkan aracımız, öğleden sonra Niğde'deki yeni adresinize ulaşır ve kurulum işlemlerine başlanır.";
export const pricingText = "Mersin Niğde evden eve nakliyat fiyatları 18.000 TL ile 24.500 TL aralığında bütçelendirilmektedir. Fiyat tekliflerimize K3 belgeli kapalı kasa nakliye kamyonu, kalın koruyucu ambalaj malzemeleri, uzman marangoz montaj desteği, emtia nakliyat sigortası ve asansör kurulumu dahildir. 1+1 daire nakliyesi 18.000 TL - 19.500 TL aralığında bütçelendirilirken; 2+1 daireler 20.000 TL - 21.500 TL, 3+1 daireler ise 22.500 TL - 24.500 TL aralığında taşınmaktadır.";
export const routeText = "Mersin'den Niğde'ye giden nakliye araçlarımız, otoyol konforu sunan O-21 Mersin-Ankara otoyolunu kullanır. Güzergâh sırasıyla Mersin - Tarsus - Pozantı - Gülek Boğazı - Ulukışla üzerinden Niğde merkeze ulaşır. Pozantı geçişindeki dik rampalarda ve tünellerde araçlarımız emniyet kurallarına uygun hız limitlerinde ilerler. Otoyol kalitesi sayesinde eşyalarınız minimum sarsıntıya maruz kalır.";
export const insuranceText = "Mersin Niğde arası tüm ev taşıma hizmetlerimiz, Anadolu Sigorta aracılığıyla geniş kapsamlı emtia nakliyat sigortası kapsamındadır. Eşyalarınız yoldaki olası kaza, devrilme, yangın risklerinin yanı sıra yükleme ve boşaltma esnasında oluşabilecek hasarlara karşı da sigorta poliçesiyle tam bedeli üzerinden yasal teminat altındadır.";
export const tipsText = "Niğde'ye taşınırken özellikle Pozantı otoban geçişindeki dağ tünellerinde ve Gülek boğazında kış aylarında yaşanabilecek yoğun kar yağışı ve buzlanma durumları ekiplerimizce yakından takip edilir. Araçlarımız mevsim şartlarına uygun kış ekipmanlarıyla sevk edilir. Niğde merkez ve Bor ilçesindeki yüksek katlı sitelerde asansör kurulum açısı taşınma günü öncesinde planlanmaktadır.";
export const faq = [
  {"question":"Mersin Niğde nakliyat kaç saat sürer?","answer":"İki şehir arası karayolu mesafesi ortalama 2.5 saattir. Yükleme ve boşaltma dahil tüm süreç aynı gün içinde 5-7 saatte tamamlanır."},
  {"question":"Bor ilçesine de hizmet veriyor musunuz?","answer":"Evet, Niğde'nin Bor, Ulukışla, Çiftlik, Çamardı başta olmak üzere tüm ilçelerine günlük nakliye hizmeti sunuyoruz."},
  {"question":"Fiyatlarınız taşınma günü değişir mi?","answer":"Hayır, ücretsiz ekspertiz sonrasında karşılıklı imzalanan sözleşmede yer alan sabit fiyat taşınma günü kesinlikle değiştirilmez."},
  {"question":"Mobilya montajı fiyata dahil midir?","answer":"Evet, yatak odası gardırobu, yemek masası ve demonte mobilyaların söküm ve kurulum işlemleri fiyatlarımıza dahildir."},
  {"question":"Asansörlü nakliyat yapıyor musunuz?","answer":"Evet, binaların kat durumuna ve asansör kurulum açısının uygunluğuna göre 25. kata kadar asansör kurarak eşyalarınızı pencerelerden taşıyoruz."},
  {"question":"Niğde'den Mersin'e dönüş nakliyesi var mı?","answer":"Evet, Niğde-Mersin yönünde de haftalık dönüş araçlarımızla uygun fiyatlı parça eşya ve komple ev nakliyesi yapmaktayız."}
];
