export const introText = "Mersin Uzman Eller Nakliyat, Mersin'den Osmaniye'ye (Kadirli, Düziçi dahil) yasal K3 belgeli kapalı kasa araçları, teleskopik eşya asansörleri ve deneyimli kadrolarıyla profesyonel evden eve nakliye hizmetleri sunmaktadır. Doğu Akdeniz otoyol hattındaki yoğun seferlerimiz sayesinde eşyalarınızı aynı gün içerisinde yeni adresinize sıfır hasar ilkesiyle ulaştırıyoruz. Uzman Eller Nakliyat güvencesiyle Osmaniye taşımalarınızda sabit fiyat ve marangoz montaj garantisi sunulur.";
export const distanceText = "Mersin ile Osmaniye arası karayolu mesafesi TAG otoyolu üzerinden yaklaşık 180 kilometredir ve nakliye kamyonlarımızla seyahat süresi ortalama 2.2 saattir. Kısa mesafe avantajı sayesinde sabah saat 08:00'de başlayan paketleme ve yükleme işlemleri sonrasında, kamyonumuz aynı gün öğlen saatlerinde yola çıkar ve öğleden sonra Osmaniye'deki adresinizde anahtar teslim kurulum tamamlanır.";
export const pricingText = "Mersin Osmaniye evden eve nakliyat fiyatları daire oda sayısına göre 17.000 TL ile 23.000 TL arasında değişmektedir. Fiyat tekliflerimize K3 belgeli kapalı kasa kamyon, havalı kalın ambalaj malzemeleri, uzman marangoz de-montaj ve kurulum işçiliği, Anadolu Sigorta emtia sigortası ve asansör kurulumu dahildir. 1+1 daireler 17.000 TL - 18.500 TL, 2+1 daireler 19.000 TL - 20.500 TL, 3+1 daireler ise 21.000 TL - 23.000 TL aralığında taşınmaktadır.";
export const routeText = "Mersin'den Osmaniye'ye giden nakliye araçlarımız, bölünmüş duble yol ve otoyol standardına sahip O-52 TAG otoyolunu kullanır. Güzergâh sırasıyla Mersin - Tarsus - Adana - Ceyhan - Toprakkale üzerinden Osmaniye merkeze ulaşır. Yol tamamen düz ve otoban standartlarında olduğundan eşyaların sarsılma veya hasar görme riski sıfıra yakındır.";
export const insuranceText = "Mersin Osmaniye arası yürüttüğümüz tüm ev taşıma hizmetleri, Anadolu Sigorta güvencesiyle geniş kapsamlı emtia taşıma sigortası kapsamındadır. Eşyalarınız yoldaki olası kaza, yangın, devrilme gibi hasar risklerine karşı sigortalanarak güvenceye alınır. Poliçeniz taşınma öncesinde adınıza düzenlenerek size sunulmaktadır.";
export const tipsText = "Osmaniye'ye taşınırken Kadirli ve Düziçi gibi engebeli veya dar sokak yapısına sahip ilçelerde asansör kurulum alanının açık olması ve site yönetiminin kuralları önem taşır. Ekiplerimiz taşınma öncesinde fiziki koşulları planlayarak gerekli güvenlik önlemlerini alır ve zaman kaybı yaşanmasını önler.";
export const faq = [
  {"question":"Mersin Osmaniye nakliyat kaç saat sürer?","answer":"Mesafe yakın olduğu için sürüş süresi yaklaşık 2 saat 15 dakikadır. Yükleme, yol ve montaj dahil tüm süreç 5-7 saatte tamamlanır."},
  {"question":"Kadirli ve Düziçi ilçelerine hizmet veriyor musunuz?","answer":"Evet, Osmaniye'nin Kadirli, Düziçi, Bahçe ve Kadirli başta olmak üzere tüm ilçelerine günlük nakliye seferlerimiz vardır."},
  {"question":"Marangozluk hizmetleriniz neleri kapsar?","answer":"Yatak odası gardırobu, raylı dolaplar ve demonte mobilyaların sökülmesi, paketlenmesi ve yeni evde kurulması işlemlerini kapsar."},
  {"question":"Osmaniye'de yüksek katlara asansör kuruluyor mu?","answer":"Evet, Osmaniye genelinde asansör kurulumuna uygun pencere veya balkonu olan tüm binalarda 25. kata kadar asansör kuruyoruz."},
  {"question":"Sözleşme imzalıyor musunuz?","answer":"Evet, karşılıklı ıslak imzalı sözleşme imzalayarak anlaşılan sabit fiyatı ve tüm lojistik detayları güvence altına alıyoruz."},
  {"question":"Klima sökümü yapıyor musunuz?","answer":"Klima söküm ve montajı elektrik ve gaz tesisatı uzmanlığı gerektirdiğinden dahil değildir, ancak anlaşmalı servisle yönlendirebiliyoruz."}
];
