export const introText = "Mersin Uzman Eller Nakliyat, Mersin'den Karaman'a (Ermenek dahil) yasal K3 yetki belgeli nakliye tır ve kamyonları, mobil dış cephe eşya asansörleri ve uzman kadrolarıyla profesyonel evden eve taşıma hizmeti vermektedir. Toros dağ geçişlerinde tecrübeli şoförlerimiz ve kadrolu marangozlarımız eşyalarınızı sıfır hasar güvencesiyle yeni adresinize ulaştırır. Uzman Eller Nakliyat olarak, Karaman güzergahındaki tüm operasyonlarımızda sabit fiyat ve yazılı sözleşme garantisi sunmaktayız.";
export const distanceText = "Mersin ile Karaman arası karayolu mesafesi Sertavul geçidi üzerinden yaklaşık 240 kilometredir. Nakliye kamyonlarımızla seyahat süresi ortalama 3.5 saattir. Sabah saat 08:00'de başlayan eşya paketleme ve yükleme adımlarının ardından öğle saatlerinde hareket eden aracımız, öğleden sonra Karaman'a ulaşır ve montaj işlemlerini aynı gün akşam saatlerine kadar tamamlar.";
export const pricingText = "Mersin Karaman arası nakliyat fiyatları dairenin büyüklüğüne ve kat durumlarına bağlı olarak 19.000 TL ile 26.000 TL arasında değişmektedir. Fiyatlarımıza K3 belgeli kapalı kasa araç sevkıyatı, koruyucu ambalaj malzemeleri, uzman marangoz de-montaj ve montaj işçilikleri, emtia sigortası ve asansör kurulumu dahildir. 1+1 daire taşıma bedeli 19.000 TL - 20.500 TL, 2+1 daire taşıma 24.000 TL - 26.000 TL, 3+1 daire taşıma ise 24.000 TL - 26.000 TL aralığındadır.";
export const routeText = "Mersin'den Karaman'a giden nakliye araçlarımız, Mersin - Silifke - Mut - Sertavul Geçidi - Karaman karayolu hattını takip eder. Yolun büyük bölümü bölünmüş duble yol standartlarında olup sürüş konforu yüksektir. Mut-Sertavul geçidindeki dik rampalarda ve virajlarda araçlarımız güvenlik sınırları dahilinde yavaş seyrederek eşyaların sarsılmasını önler.";
export const insuranceText = "Mersin Karaman arası ev taşıma operasyonlarımızın tamamı Anadolu Sigorta güvencesiyle geniş kapsamlı emtia taşıma sigortası kapsamındadır. Eşyalarınız yoldaki olası devrilme, kaza, yangın risklerinin yanı sıra apartman içi taşıma esnasında oluşabilecek kazaen hasarlara karşı da poliçe güvencesi altındadır.";
export const tipsText = "Karaman'a taşınırken özellikle Sertavul geçidindeki hava durumları ekiplerimizce yakından takip edilir. Kış geçişlerinde araçlarımızda kar lastiği, çekme halatı ve zincir donanımları eksiksiz bulundurulmaktadır. Karaman merkezindeki yeni konut sitelerinde yük asansörü izinleri ve asansör kurulum açısı taşınma günü öncesinde planlanmaktadır.";
export const faq = [
  {"question":"Mersin Karaman nakliyat kaç saat sürer?","answer":"Mersin ile Karaman arası sürüş süresi yaklaşık 3.5 saattir. Paketleme, yükleme, yol ve montaj dahil tüm süreç aynı gün 6-8 saatte tamamlanır."},
  {"question":"Ermenek ilçesine ev taşıyor musunuz?","answer":"Evet, Karaman'ın Ermenek, Kazımkarabekir, Ayrancı başta olmak üzere tüm dış ilçelerine nakliye hizmeti sunuyoruz."},
  {"question":"Fiyatlar taşınma günü değişir mi?","answer":"Hayır, ücretsiz ekspertiz sonrasında karşılıklı imzalanan sözleşmede yer alan sabit fiyat taşınma günü kesinlikle değiştirilmez."},
  {"question":"Marangoz montajı fiyata dahil midir?","answer":"Evet, yatak odası raylı dolapları, mobilyaların söküm ve montajı ile beyaz eşya bağlantıları fiyata dahildir."},
  {"question":"Asansörlü taşıma yapıyor musunuz?","answer":"Evet, binaların kat durumuna ve kurulum açısının uygunluğuna göre 25. kata kadar asansör kurarak eşyalarınızı pencerelerden taşıyoruz."},
  {"question":"Karaman'dan Mersin'e dönüş nakliyesi var mı?","answer":"Evet, Karaman-Mersin yönünde de haftalık dönüş araçlarımızla uygun fiyatlı parça eşya ve komple ev nakliyesi yapmaktayız."}
];
