export const introText = "Mersin Uzman Eller Nakliyat, Mersin'den Hatay'ın tüm ilçelerine (Antakya, İskenderun, Defne, Kırıkhan, Samandağ dahil) güvenli, K3 yasal yetki belgeli araç filomuzla asansörlü ve marangozlu evden eve nakliyat çözümleri sunmaktadır. Hatay lojistik hattımızda haftalık düzenli seferler düzenleyen deneyimli şoförlerimiz ve kadrolu ambalaj ekiplerimiz, eşyalarınızın yeni adresinize sıfır hasar ilkesiyle taşınmasını garanti eder. Mersin Hatay güzergahında yürüttüğümüz tüm taşınma operasyonlarında ücretsiz ekspertiz ve yazılı sözleşme güvencesi sunuyoruz.";
export const distanceText = "Mersin ile Hatay arası karayolu mesafesi yaklaşık 200 kilometredir ve ev eşyası taşıyan nakliye kamyonlarımız için sürüş süresi ortalama 2.5 saattir. Sabah saat 08:00'de Mersin'deki adresinizde başlayan paketleme ve yükleme işlemlerinin ardından, aracımız otoyol üzerinden yola çıkar. Aynı gün öğleden sonra Hatay'daki yeni adresinize ulaşan ekiplerimiz, eşyaların indirilmesi, marangoz montajı ve beyaz eşya bağlantılarının yapılmasıyla taşınma sürecini gün sona ermeden tamamlar.";
export const pricingText = "Mersin Hatay arası ev taşıma fiyatları 18.000 TL ile 25.000 TL arasında bütçelendirilmektedir. Fiyat tekliflerimize K3 belgeli kapalı kasa taşıma kamyonu, kalın koruyucu ambalaj malzemeleri, uzman marangoz de-montaj ve montaj işçiliği, emtia nakliyat sigortası poliçesi ve asansör kurulumu dahildir. 1+1 daire nakliyesi 18.000 TL - 20.000 TL aralığında bütçelendirilirken; 2+1 daireler 21.000 TL - 22.500 TL, 3+1 ve üzeri geniş daireler ise 23.000 TL - 25.000 TL aralığında taşınmaktadır.";
export const routeText = "Mersin'den Hatay'a giden nakliye araçlarımız, bölünmüş duble yol ve otoyol kalitesine sahip O-52 TAG otoyolunu kullanır. Güzergâh sırasıyla Mersin - Tarsus - Adana - Ceyhan - Dörtyol - İskenderun - Belen geçidi üzerinden Antakya merkeze ulaşır. Belen geçidindeki dik rampalarda sürüş emniyeti kuralları ve hız limitleri hassasiyetle gözetilir. TAG otoyolu otoyol kalitesi sayesinde eşyalarınız yolculuk boyunca minimum sarsıntıya maruz kalır.";
export const insuranceText = "Uzman Eller Nakliyat olarak şehirlerarası tüm seferlerimizde olduğu gibi Mersin Hatay taşımalarımızda da Anadolu Sigorta güvencesiyle geniş kapsamlı emtia taşıma sigortası sunuyoruz. Eşyalarınız yükleme anından yeni evinizde montajı tamamlanana kadar yol kazaları, doğal afet, yangın ve hırsızlık risklerine karşı yasal teminat altına alınır. Adınıza düzenlenen resmi sigorta poliçesi, taşınma öncesinde tarafınıza teslim edilir.";
export const tipsText = "Hatay'a taşınırken özellikle Antakya ve İskenderun ilçelerindeki yeni yerleşim sitelerinde yer alan yüksek kat durumlarına dikkat edilmelidir. Bina içi yük asansörünün kullanım kuralları önceden site yönetiminden öğrenilmelidir. Merdivenlerin dar olması durumunda dış cephe mobil asansör kurulum alanı ekiplerimizce önceden analiz edilir. Ayrıca Belen geçidindeki ani sis ve yağış durumları için araçlarımızın teknik donanımları mevsim şartlarına uygun olarak sevk edilmektedir.";
export const faq = [
  {"question":"Mersin Hatay nakliyat kaç saat sürer?","answer":"Mersin ile Hatay arası karayolu sürüşü yaklaşık 2.5 saat sürer. Yükleme, yolculuk ve montaj dahil tüm süreç aynı gün içerisinde ortalama 6-8 saatte biter."},
  {"question":"İskenderun'da yüksek katlı dairelere asansör kuruluyor mu?","answer":"Evet, İskenderun ve Hatay genelinde 25. kata kadar ulaşabilen teleskopik mobil dış cephe asansörlerimizle hizmet veriyoruz."},
  {"question":"Fiyat teklifine montaj işçilikleri dahil midir?","answer":"Evet, gardırop söküm ve montajı, yatak odası üniteleri kurulumu ve beyaz eşyaların bağlantısı ücretsiz olarak fiyata dahildir."},
  {"question":"Hatay'dan Mersin'e dönüş taşıması yapıyor musunuz?","answer":"Evet, Hatay-Mersin yönünde de haftalık düzenli dönüş seferlerimizle ekonomik parça eşya ve ev taşıma hizmeti veriyoruz."},
  {"question":"Sözleşme imzalıyor musunuz?","answer":"Evet, taşınma öncesinde anlaşılan tüm detayları ve sabit fiyatı yasal güvenceye alan ıslak imzalı nakliye sözleşmesi imzalıyoruz."},
  {"question":"Kırılacak mutfak eşyalarını paketliyor musunuz?","answer":"Talep etmeniz halinde mutfak bardakları ve porselenleriniz özel Kraft ambalaj kağıtları ile sarılarak kolilenir. Bu hizmet ek ücrete tabidir."}
];
