export const introText = "Mersin Uzman Eller Nakliyat, Mersin'den Konya'nın tüm ilçerine (Selçuklu, Meram, Karatay, Ereğli dahil) K3 yasal yetki belgeli araç filosu, mobil dış cephe eşya asansörleri ve uzman kadrolarıyla profesyonel evden eve taşımacılık hizmeti sunmaktadır. Toroslar üzerinden İç Anadolu bölgesine uzanan lojistik hattımızda, eşyalarınızın her türlü sarsıntıya ve hava koşuluna karşı güvenle taşınmasını sağlıyoruz. Uzman Eller Nakliyat kalitesiyle Konya taşımalarınızda sabit fiyat ve marangoz montaj garantisi sunulur.";
export const distanceText = "Mersin ile Konya arası karayolu mesafesi Sertavul geçidi güzergahı üzerinden yaklaşık 350 kilometredir. Ev eşyası yüklü nakliye araçlarımızın seyir süresi ortalama 4.5 saattir. Operasyon sabah saat 08:00'de Mersin'deki adresinizde paketleme ile başlar, öğlen saatlerinde yola çıkan aracımız akşamüstü Konya'daki yeni adresinize ulaşır ve aynı gün eşyalarınızın kurulumu tamamlanır.";
export const pricingText = "Mersin Konya evden eve nakliyat fiyatları 21.500 TL ile 29.000 TL arasında değişiklik göstermektedir. Fiyatlandırma eşya hacmi, daire oda sayısı, asansör gereksinimi ve kat durumlarına göre belirlenmektedir. Tekliflerimize K3 belgeli kapalı kasa kamyon, kalın patpat ambalaj malzemeleri, uzman marangoz montaj desteği, emtia sigortası ve asansör kurulumu dahildir. 1+1 daireler 21.500 TL - 23.000 TL, 2+1 daireler 27.000 TL - 29.000 TL, 3+1 daireler ise 27.000 TL - 29.000 TL aralığında taşınmaktadır.";
export const routeText = "Mersin'den Konya'ya giden nakliye araçlarımız, Mersin - Mut - Sertavul Geçidi - Karaman - Konya karayolu güzergahını kullanır. Toros dağlarının en önemli geçiş noktalarından olan Sertavul geçidinde kış aylarında sürüş emniyeti kuralları en üst düzeyde uygulanır. Ekiplerimiz bölünmüş çift şeritli yollar üzerinden hasarsız ve sarsıntısız bir transfer süreci gerçekleştirir.";
export const insuranceText = "Mersin Konya arası tüm ev taşıma hizmetlerimiz, Anadolu Sigorta aracılığıyla geniş kapsamlı emtia nakliyat sigortası güvencesi altındadır. Eşyalarınız yoldaki olası kaza, yangın, devrilme risklerinin yanı sıra yükleme ve boşaltma esnasında oluşabilecek hasarlara karşı da sigorta poliçesi kapsamında tam bedel üzerinden güvenceye alınır.";
export const tipsText = "Konya'ya taşınırken özellikle Selçuklu ve Meram bölgelerindeki yüksek katlı modern sitelerin kurallarına dikkat edilmelidir. Taşınma öncesinde site yönetiminden asansör kurulum izni alınmalıdır. Ayrıca kış aylarında Sertavul geçişinde yaşanabilecek yoğun kar yağışı ve buzlanma risklerine karşı araçlarımızın kış lastiği ve zincir ekipmanları eksiksiz sevk edilmektedir.";
export const faq = [
  {"question":"Mersin Konya nakliyat kaç saat sürer?","answer":"Mersin ile Konya arası sürüş süresi yaklaşık 4.5 saattir. Tüm taşınma süreci (yükleme, yol ve montaj dahil) aynı gün içinde 7-9 saatte tamamlanır."},
  {"question":"Ereğli ilçesine de hizmet veriyor musunuz?","answer":"Evet, Konya'nın Ereğli, Akşehir, Beyşehir başta olmak üzere tüm dış ilçelerine günlük evden eve nakliye hizmetimiz vardır."},
  {"question":"Konya'da asansörlü taşıma yapıyor musunuz?","answer":"Evet, Konya'daki yeni adresinizde dış cephe asansör kurulumuna uygun balkon veya pencere bulunması durumunda 25. kata kadar asansör kuruyoruz."},
  {"question":"Mobilya montajı fiyata dahil midir?","answer":"Evet, yatak odası gardırobu, yemek masası ve temel demonte mobilyaların söküm ve kurulum işlemleri fiyatlarımıza dahildir."},
  {"question":"Eşyaların sigortalanması ekstra ücret gerektirir mi?","answer":"Hayır, sunduğumuz tüm şehirlerarası fiyat tekliflerine emtia nakliyat sigortası ücretsiz olarak dahildir."},
  {"question":"Rezervasyon için ne kadar önceden aramalıyım?","answer":"Özellikle yaz tayin dönemlerinde yoğunluk yaşandığı için taşınma tarihinizden en az 5-7 gün önce rezervasyon yaptırmanızı tavsiye ederiz."}
];
